source "http://rubygems.org"

# Specify your gem's dependencies in frank-cucumber.gemspec
gemspec


# override the gemspec dependency for local development of sim-launcher
gem 'sim_launcher', :github => 'rhgills/Sim-Launcher', :branch => 'master'